markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Shivam Vats
url: https://shivamvats.github.io/
description: Getting better
avatar: https://avatars0.githubusercontent.com/u/6918975?v=3&s=460

github: shivamvats
linkedin: shivamvats
